### ISSUE TITLE
how can i build s x86?

### ISSUE THREAD

**Issue by VC1W** [ifBars/ImGuiDX9-KeyAuth-Loader-Example#1]
can you make it possible to build as x86?

**Comment by ifBars** [comment]
You shouldn't run into any issues at all when trying to build x86, literally all you have to do is change the build from x64 to x86 in visual studio, and then compile it.

**Comment by VC1W** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	E1696	cannot open source file "DirectXTex.h"

**Comment by VC1W** [comment]
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	LNK1181	cannot open input file 'library_x64.lib'

**Comment by ifBars** [comment]
> Severity	Code	Description	Project	File	Line	Suppression State	Details
> 
> Error (active)	E1696	cannot open source file "DirectXTex.h"

I am not your paid support agent, if you cannot figure out from that message that DirectXTex (The Image Library I Used for DX9) does not work on x64, then you shouldn't be using this repo in the first place. The project is meant for people who know how to code, and know what they are doing. Obviously you're going to have to make a few tweaks when changing between x64 and x86. 

Long story short, either remove direct x tex as a whole, or substitute it with a different library. Either way you're going to have to know what you are doing, and i'm not here to teach you how. Your best bet is just removing directxtex library and just not using images. Good luck lol

**Comment by VC1W** [comment]
nah i fixed that sht

**Comment by VC1W** [comment]
but either you forgot to include the like x86 keyauth lib and x64 and libcurl. if you have a version you know works to build as x86 cant you just upload that?

**Comment by ifBars** [comment]
> nah i fixed that sht

Then i'm not sure why you're here asking me to fix it for you. If you find an actual issue with the code, then feel free to post an issue, but when this one purely an user error on your part.

**Comment by ifBars** [comment]
> but either you forgot to include the like x86 keyauth lib and x64 and libcurl. if you have a version you know works to build as x86 cant you just upload that?

I only included the files needed for it to work as is. The project is provided **AS IS**. That means it is **YOUR** responsibility to migrate it to c64/x86, meaning if you want to change anything, you have to include the files relevant for that change yourself.

**Comment by VC1W** [comment]
unresolved externals mate

**Comment by VC1W** [comment]
do you use the latest verion fo keyauth or?

**Comment by ifBars** [comment]
> unresolved externals mate

Again, user error on your part. Project is provided **AS IS**, which is x64 build. It is your responsibility to link all the required files for x86, along with everything else needed to migrate from 64 to 86. As for the key auth version, it's not that hard to check for yourself... I mean it's literally one of the first maybe 20-25 lines of code in the main app? Did you even bother to check for yourself. This repo hasn't been updated in months, nor will it ever likely be updated again. So, as I have already said 3 times, **THE PROJECT IS PROVIDED AS IS, IT IS YOUR RESPONSIBILITY TO MAKE THE NECESSARY CHANGES.**

**Comment by VC1W** [comment]
well thanks anyway, maybe i will learn something from doing it myself
